### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by CRAG666** [dawsers/hyprscroller#4] opened 2024-03-31 21:19 UTC
ew && PKG_CONFIG_PATH="/home/think-crag/.local/share/hyprpm/headersRoot/share/pkgconfig" make release
g++ -fPIC -fno-gnu-unique -std=c++2b -O3 -DWLR_USE_UNSTABLE \
    -MT src/main.o -MMD -MP -MF src/main.d \
    `pkg-config --cflags pixman-1 libdrm hyprland` \
    -c src/main.cpp -o src/main.o
En el fichero incluido desde /home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../Window.hpp:8,
                 desde /home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/ConfigManager.hpp:16,
                 desde src/main.cpp:1:
/home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../config/ConfigDataValues.hpp: In member function ‘virtual std::string CGradientValueData::toString()’:
/home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../config/ConfigDataValues.hpp:64:5: aviso: no hay una declaración de devolución en la función que no devuelve void [-Wreturn-type]
   64 |     }
      |     ^
src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:17:152: error: asignador C99 ‘data’ fuera del inicializador agregado
   17 |     HyprlandAPI::addConfigValue(PHANDLE, "plugin:scroller:col.freecolumn_border", SConfigValue{.data = std::make_shared<CGradientValueData>(0xff9e1515)});
      |                                                                                                                                                        ^
src/main.cpp:17:152: error: uso no válido del tipo incompleto ‘struct SConfigValue’
En el fichero incluido desde src/main.cpp:2:
/home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/PluginAPI.hpp:63:8: nota: forward declaration of ‘struct SConfigValue’
   63 | struct SConfigValue;
      |        ^~~~~~~~~~~~
make: *** [Makefile:18: src/main.o] Error 1

**Comment by dawsers** [comment] 2024-03-31 21:26
You are using a newer version of Hyprland than 0.35. I am working on supporting the current version. Check back in a few hours!

**Comment by dawsers** [comment] 2024-03-31 23:00
Try again. I don't have Hyprland 0.37.1 on my system, but I think it should compile now. If it doesn't, let me know. Otherwise, please close this issue.

**Comment by CRAG666** [comment] 2024-04-01 03:28
ew && PKG_CONFIG_PATH="/home/think-crag/.local/share/hyprpm/headersRoot/share/pkgconfig" make release
cmake -B ./Release -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Checking for modules 'hyprland;pixman-1;libdrm'
--   Found hyprland, version 0.37.1
--   Found pixman-1, version 0.43.4
--   Found libdrm, version 2.4.120
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/new/Release
cmake --build ./Release -j
make[1]: se entra en el directorio '/tmp/hyprpm/new/Release'
[ 50%] Building CXX object CMakeFiles/hyprscroller.dir/src/main.cpp.o
[ 50%] Building CXX object CMakeFiles/hyprscroller.dir/src/dispatchers.cpp.o
[ 75%] Building CXX object CMakeFiles/hyprscroller.dir/src/scroller.cpp.o
/tmp/hyprpm/new/src/scroller.cpp:3:10: error fatal: hyprland/src/desktop/Window.hpp: No existe el fichero o el directorio
    3 | #include <hyprland/src/desktop/Window.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilación terminada.
make[3]: *** [CMakeFiles/hyprscroller.dir/build.make:104: CMakeFiles/hyprscroller.dir/src/scroller.cpp.o] Error 1
make[3]: *** Se espera a que terminen otras tareas....
En el fichero incluido desde /home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../Window.hpp:8,
                 desde /home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/ConfigManager.hpp:16,
                 desde /tmp/hyprpm/new/src/main.cpp:1:
/home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../config/ConfigDataValues.hpp: In member function ‘virtual std::string CGradientValueData::toString()’:
/home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../config/ConfigDataValues.hpp:64:5: aviso: no hay una declaración de devolución en la función que no devuelve void [-Wreturn-type]
   64 |     }
      |     ^
En el fichero incluido desde /home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../Window.hpp:8,
                 desde /home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/ConfigManager.hpp:16,
                 desde /home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:10,
                 desde /tmp/hyprpm/new/src/dispatchers.cpp:1:
/home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../config/ConfigDataValues.hpp: In member function ‘virtual std::string CGradientValueData::toString()’:
/home/think-crag/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../config/ConfigDataValues.hpp:64:5: aviso: no hay una declaración de devolución en la función que no devuelve void [-Wreturn-type]
   64 |     }
      |     ^
make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hyprscroller.dir/all] Error 2
make[1]: *** [Makefile:91: all] Error 2
make[1]: se sale del directorio '/tmp/hyprpm/new/Release'
make: *** [Makefile:13: release] Error 2
@dawsers

**Comment by dawsers** [comment] 2024-04-01 11:51
Please, run `hyprctl systeminfo` and copy the results here. I need to know the exact version of Hyprland you are running. `hyprpm` only supports very specific versions given by *commit pins* or it will default to the trunk revision. You may need another version or a manual build.

**Comment by aacebedo** [comment] 2024-04-02 16:35
Latest version does not build:
- it is missing scrolllayout before predictSizeForNewWindowTiled() so it leads to an undefined symbol
- Window.hpp has been moved in 0.38.0

With the modification it does not work at all. All windows seems to be sent out of viewport of the monitor. Reproduced on 0.37.1 and 0.38.0

**Comment by dawsers** [comment] 2024-04-02 17:20
Please, try to build again with the latest commit. I can check it builds, but I cannot check it works correctly, as I don't have anything other than 0.35 on my system. I am in the process of building a virtual machine to be able to test...

**Comment by aacebedo** [comment] 2024-04-02 18:47
Unfortunately it does not work either. Windows disappears. I do not have this behavior with other plugins. 
I think you do not need a VM for that and you shall be able to compile it on a temp directory.

**Comment by dawsers** [comment] 2024-04-02 19:11
I use a nested Hyprland session to debug, and that works for as long as the version is the same as the one in the system. I can compile a different version of Hyprland in a temp dir like you suggest, together with the dependencies that are different than the ones on my system (hyprcursors, hyprlang). The problem is when running it, it tries to use two versions of hyprlang (the one I compile and link against and the one on my system) even if I use LD_LIBRARY_PATH, and it crashes. I think a tty would have the same problem. I am sure this can be fixed, but it is not evident. I spent a full afternoon this weekend trying to make that work and I couldn't work around the problem.

When running locally, there is a conflict

**Comment by aacebedo** [comment] 2024-04-02 19:16
Ok understood. tty won't prevent you from that I guess. I've never tried to run wayland compositors within docker either. So even with that isolation I don't know if it will work.

**Comment by dawsers** [comment] 2024-04-02 19:19
I also tried with podman and distrobox (similar). The problem is when you want graphical output, it links the container to the system's compositor (or X) sockets, so you can actually see things. At that point, you are again trying to nest two different versions of the compositor, and it crashes. So I use that container to compile the code for v0.37.1, but I cannot test it until I do the VM thing.

**Comment by dawsers** [comment] 2024-04-03 10:18
This should be fixed now. There is currently support for Hyprland 0.35 and 0.38.0. The trunk version is not working because of recent changes I don't want to follow for now until things stabilize upstream. I removed support for v0.37.1. I will only follow the version I use and the latest tagged one from now on. Let me know how it goes...

**Closed** 2024-04-03 15:33 UTC
